// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSocialUserID holds the string denoting the social_user_id field in the database.
	FieldSocialUserID = "social_user_id"
	// FieldSocialAvatarURL holds the string denoting the social_avatar_url field in the database.
	FieldSocialAvatarURL = "social_avatar_url"
	// FieldSocialEmail holds the string denoting the social_email field in the database.
	FieldSocialEmail = "social_email"
	// FieldSocialName holds the string denoting the social_name field in the database.
	FieldSocialName = "social_name"
	// FieldSocialType holds the string denoting the social_type field in the database.
	FieldSocialType = "social_type"
	// FieldSocialPayload holds the string denoting the social_payload field in the database.
	FieldSocialPayload = "social_payload"
	// FieldHeroRepeat holds the string denoting the hero_repeat field in the database.
	FieldHeroRepeat = "hero_repeat"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"

	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldSocialUserID,
	FieldSocialAvatarURL,
	FieldSocialEmail,
	FieldSocialName,
	FieldSocialType,
	FieldSocialPayload,
	FieldHeroRepeat,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// DefaultSocialUserID holds the default value on creation for the social_user_id field.
	DefaultSocialUserID string
	// DefaultSocialAvatarURL holds the default value on creation for the social_avatar_url field.
	DefaultSocialAvatarURL string
	// DefaultSocialEmail holds the default value on creation for the social_email field.
	DefaultSocialEmail string
	// DefaultSocialName holds the default value on creation for the social_name field.
	DefaultSocialName string
	// DefaultSocialType holds the default value on creation for the social_type field.
	DefaultSocialType string
	// DefaultSocialPayload holds the default value on creation for the social_payload field.
	DefaultSocialPayload string
	// DefaultHeroRepeat holds the default value on creation for the hero_repeat field.
	DefaultHeroRepeat uint
)
