// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID                = "id"                   // FieldLatestHeroScore holds the string denoting the latest_hero_score vertex property in the database.
	FieldLatestHeroScore   = "latest_hero_score"    // FieldBetterHeroScore holds the string denoting the better_hero_score vertex property in the database.
	FieldBetterHeroScore   = "better_hero_score"    // FieldBetterHeroScoreAt holds the string denoting the better_hero_score_at vertex property in the database.
	FieldBetterHeroScoreAt = "better_hero_score_at" // FieldSocialUserID holds the string denoting the social_user_id vertex property in the database.
	FieldSocialUserID      = "social_user_id"       // FieldSocialAvatarURL holds the string denoting the social_avatar_url vertex property in the database.
	FieldSocialAvatarURL   = "social_avatar_url"    // FieldSocialEmail holds the string denoting the social_email vertex property in the database.
	FieldSocialEmail       = "social_email"         // FieldSocialName holds the string denoting the social_name vertex property in the database.
	FieldSocialName        = "social_name"          // FieldSocialType holds the string denoting the social_type vertex property in the database.
	FieldSocialType        = "social_type"          // FieldSocialPayload holds the string denoting the social_payload vertex property in the database.
	FieldSocialPayload     = "social_payload"       // FieldHeroPlayed holds the string denoting the hero_played vertex property in the database.
	FieldHeroPlayed        = "hero_played"          // FieldHeroRepeat holds the string denoting the hero_repeat vertex property in the database.
	FieldHeroRepeat        = "hero_repeat"          // FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt         = "created_at"           // FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt         = "updated_at"

	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldLatestHeroScore,
	FieldBetterHeroScore,
	FieldBetterHeroScoreAt,
	FieldSocialUserID,
	FieldSocialAvatarURL,
	FieldSocialEmail,
	FieldSocialName,
	FieldSocialType,
	FieldSocialPayload,
	FieldHeroPlayed,
	FieldHeroRepeat,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// DefaultLatestHeroScore holds the default value on creation for the latest_hero_score field.
	DefaultLatestHeroScore int
	// DefaultBetterHeroScore holds the default value on creation for the better_hero_score field.
	DefaultBetterHeroScore int
	// DefaultSocialUserID holds the default value on creation for the social_user_id field.
	DefaultSocialUserID string
	// DefaultSocialAvatarURL holds the default value on creation for the social_avatar_url field.
	DefaultSocialAvatarURL string
	// DefaultSocialEmail holds the default value on creation for the social_email field.
	DefaultSocialEmail string
	// DefaultSocialName holds the default value on creation for the social_name field.
	DefaultSocialName string
	// DefaultSocialType holds the default value on creation for the social_type field.
	DefaultSocialType string
	// DefaultSocialPayload holds the default value on creation for the social_payload field.
	DefaultSocialPayload string
	// DefaultHeroPlayed holds the default value on creation for the hero_played field.
	DefaultHeroPlayed uint
	// DefaultHeroRepeat holds the default value on creation for the hero_repeat field.
	DefaultHeroRepeat uint
)
