// Code generated by entc, DO NOT EDIT.

package prize

const (
	// Label holds the string label denoting the prize type in the database.
	Label = "prize"
	// FieldID holds the string denoting the id field in the database.
	FieldID           = "id"             // FieldSocialUserID holds the string denoting the social_user_id vertex property in the database.
	FieldSocialUserID = "social_user_id" // FieldDate holds the string denoting the date vertex property in the database.
	FieldDate         = "date"

	// Table holds the table name of the prize in the database.
	Table = "prizes"
)

// Columns holds all SQL columns for prize fields.
var Columns = []string{
	FieldID,
	FieldSocialUserID,
	FieldDate,
}

var (
	// DefaultSocialUserID holds the default value on creation for the social_user_id field.
	DefaultSocialUserID string
)
