// Code generated by entc, DO NOT EDIT.

package useractiverecord

const (
	// Label holds the string label denoting the useractiverecord type in the database.
	Label = "user_active_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldActiveType holds the string denoting the active_type field in the database.
	FieldActiveType = "active_type"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldIsFinished holds the string denoting the is_finished field in the database.
	FieldIsFinished = "is_finished"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"

	// Table holds the table name of the useractiverecord in the database.
	Table = "user_active_records"
)

// Columns holds all SQL columns for useractiverecord fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldActiveType,
	FieldScore,
	FieldIsFinished,
	FieldStartedAt,
	FieldEndedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// DefaultScore holds the default value on creation for the score field.
	DefaultScore int
	// DefaultIsFinished holds the default value on creation for the is_finished field.
	DefaultIsFinished uint
)
