// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"hero/database/ent/predicate"
	"hero/database/ent/useractiverecord"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// UserActiveRecordDelete is the builder for deleting a UserActiveRecord entity.
type UserActiveRecordDelete struct {
	config
	hooks      []Hook
	mutation   *UserActiveRecordMutation
	predicates []predicate.UserActiveRecord
}

// Where adds a new predicate to the delete builder.
func (uard *UserActiveRecordDelete) Where(ps ...predicate.UserActiveRecord) *UserActiveRecordDelete {
	uard.predicates = append(uard.predicates, ps...)
	return uard
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uard *UserActiveRecordDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uard.hooks) == 0 {
		affected, err = uard.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserActiveRecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uard.mutation = mutation
			affected, err = uard.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uard.hooks) - 1; i >= 0; i-- {
			mut = uard.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uard.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (uard *UserActiveRecordDelete) ExecX(ctx context.Context) int {
	n, err := uard.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uard *UserActiveRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: useractiverecord.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: useractiverecord.FieldID,
			},
		},
	}
	if ps := uard.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, uard.driver, _spec)
}

// UserActiveRecordDeleteOne is the builder for deleting a single UserActiveRecord entity.
type UserActiveRecordDeleteOne struct {
	uard *UserActiveRecordDelete
}

// Exec executes the deletion query.
func (uardo *UserActiveRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := uardo.uard.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{useractiverecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uardo *UserActiveRecordDeleteOne) ExecX(ctx context.Context) {
	uardo.uard.ExecX(ctx)
}
