// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserActiveRecord is the predicate function for useractiverecord builders.
type UserActiveRecord func(*sql.Selector)
